/*
 * Copyright 2025 the original author or authors from the Jeddict project (https://jeddict.github.io/).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.jeddict.ai.components;

import dev.langchain4j.agent.tool.ToolExecutionRequest;
import dev.langchain4j.data.message.SystemMessage;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.exception.AuthenticationException;
import dev.langchain4j.exception.ModelNotFoundException;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.response.ChatResponse;
import io.github.jeddict.ai.JeddictUpdateManager;
import io.github.jeddict.ai.lang.JeddictBrainListener;
import io.github.jeddict.ai.response.Response;
import io.github.jeddict.ai.response.TokenHandler;
import io.github.jeddict.ai.settings.PreferencesManager;
import io.github.jeddict.ai.util.AudioUtil;
import io.github.jeddict.ai.util.UIUtil;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;

/**
 * Purpose of this class is to receive events emitted by the JeddictBrain system
 * and react accordingly in the NetBeans platform. It is intended to be used for
 * any kind of models,  streaming and not-streaming, tooling and not tooling,
 * Q&A and agentic.
 *
 *
 * @author Shiwani Gupta
 */
public class AssistantJeddictBrainListener implements JeddictBrainListener {

    protected final AssistantChat assistantChat;
    protected JTextArea textArea;

    private final Logger LOG = Logger.getLogger(AssistantJeddictBrainListener.class.getName());

    private final PreferencesManager pm = PreferencesManager.getInstance();

    public AssistantJeddictBrainListener(AssistantChat assistantChat) {
        this.assistantChat = assistantChat;
    }

    @Override
    public void onChatStarted(final SystemMessage system, final UserMessage user) {
        LOG.finest(() ->
            "+++ starting a new chat\n-----------------------\nsystem message:\n" +
            system +
            "\nuser message:\n" +
            user +
            "\n----------");
        final String prompt = assistantChat.getQuestionPane().getText();
        SwingUtilities.invokeLater(() -> {
            assistantChat.clear();
            assistantChat.createUserQueryPane(System.out::println, prompt, Set.of());
            textArea = assistantChat.createTextAreaPane();
            assistantChat.getQuestionPane().setText("");
        });

        assistantChat.response(new Response(prompt));
    }

    @Override
    public void onRequest(final ChatRequest request) {
        //
        // Here we estimate the amount of tokens a request generates. Note that there
        // is not a standard definition of what a token is and what a model
        // shall considered a token derived from the user messages, and what instead
        // is generated by the models.
        // Models can turn the provided prompt and tool definition into something
        // more digestible for the model and count the added tokens.
        // Therefore, instead of trying to approximate closely what the AI model
        // may consider a token the estimation extracted here is based on the
        // {@code String.valueOf()} of the context's request.
        //
        SwingUtilities.invokeLater(() -> {
            //
            // TODO: we should update the UI only here and the real stats in
            // onResponse where we can use the real counts returned by the model
            //
            final int n = TokenHandler.saveInputToken(String.valueOf(request));
            assistantChat.updateLoading(
                NbBundle.getMessage(JeddictUpdateManager.class, "PROGRESS_TASK_2", n)
            );
        });
    }

    @Override
    public void onResponse(final ChatRequest request, final ChatResponse response) {
        //
        // TODO: use reponse.tokenUsage()
        //
        LOG.finest(() ->
            ">>> request\n-----------\n" +
            request +
            "\n<<< response\n-------------\n" +
            response +
            "\n----------"
        );
        final String result = response.aiMessage().text();
        assistantChat.response().addMarkdown(result);
        CompletableFuture.runAsync(() -> TokenHandler.saveOutputToken(result));
    }

    /**
     * On the execution of a tool (once done)
     *
     * @param request
     * @param result
     */
    @Override
    public void onToolExecuted(final ToolExecutionRequest request, final String result) {
        LOG.finest(() ->
            ">>> request\n-----------\n" +
            request +
            "\n<<< result\n-------------\n" +
            result +
            "\n----------"
        );
    }

    @Override
    public void onProgress(final String partialResponse, final boolean newThread) {
        LOG.finest(() ->
            "<<< partial response\n--------------------\n" +
            partialResponse +
            "\n----------");
        SwingUtilities.invokeLater(() -> {
            if (newThread && !textArea.getText().endsWith("\n")) {
                textArea.append("\n");
            }
            textArea.append(partialResponse);
        });
    }

    @Override
    public void onChatCompleted(final ChatResponse response) {
        LOG.finest(() ->
            "<<< completed response\n----------------------\n" +
            response +
            "\n----------"
        );

        //
        // just in case...
        //
        cleanup();
    }

    @Override
    public void onError(final Throwable throwable) {
        LOG.finest(() ->
            "<<< error received\n------------------\n" +
            throwable +
            "\n------------------"
        );

        // Log the error with timestamp and thread info
        LOG.log(Level.INFO, "Details:", throwable);

        onProgress(throwable.getMessage());

        cleanup();

        if (throwable instanceof AuthenticationException) {
            confirmApiKey();
        } else if (throwable instanceof ModelNotFoundException) {
            showError("Invalid model, check assistant settings.");
        } else {
            Exceptions.printStackTrace(throwable);
            showError(String.valueOf(throwable.getMessage()));
        }
    }

    @Override
    public boolean isCanceled() {
        return assistantChat.canceled;
    }

    // --------------------------------------------------------- private methods

    private void confirmApiKey() {
        JTextField apiKeyField = new JTextField(20);
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS)); // Set layout to BoxLayout

        panel.add(new JLabel("Incorrect API key. Please enter a new key:"));
        panel.add(Box.createVerticalStrut(10)); // Add space between label and text field
        panel.add(apiKeyField);

        int option = JOptionPane.showConfirmDialog(
            null, panel,
            pm.getProvider().name() + " API Key Required",
            JOptionPane.OK_CANCEL_OPTION
        );

        if (option == JOptionPane.OK_OPTION) {
            pm.setApiKey(apiKeyField.getText().trim());
        }
    }

    private void showError(final String msg) {
        JOptionPane.showMessageDialog(
            null,
            "<html>AI assistant failed to generate the requested response" +
            ((msg != null) ? (": " + msg) : "") +
            "<br>See the chat for details.",
            "Error in AI Assistant",
            JOptionPane.ERROR_MESSAGE
        );
    }

    private void cleanup() {
        assistantChat.stopLoading();
        assistantChat.getQuestionPane().setText("");
        assistantChat.updateHeight();
        assistantChat.clearFileTab();
        if (pm.isPlaySoundEnabled() && UIUtil.isWindowInBackground()) {
            AudioUtil.playNotificationSound();
        }
    }
}
