/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.github.jeddict.ai.settings;

import static io.github.jeddict.ai.models.Constant.DEEPINFRA_URL;
import io.github.jeddict.ai.models.GPT4AllModelFetcher;
import io.github.jeddict.ai.models.OllamaModelFetcher;
import io.github.jeddict.ai.models.LMStudioModelFetcher;
import io.github.jeddict.ai.scanner.ProjectClassScanner;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import static io.github.jeddict.ai.settings.GenAIModel.MODELS;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URI;

final class AIAssistancePanel extends javax.swing.JPanel {

    private final AIAssistanceOptionsPanelController controller;

    AIAssistancePanel(AIAssistanceOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        classContextPane = new javax.swing.JLayeredPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        classContextLabel = new javax.swing.JLabel();
        classContextHelp = new javax.swing.JLabel();
        classContextComboBox = new javax.swing.JComboBox<>();
        providerPane = new javax.swing.JLayeredPane();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        providerLabel = new javax.swing.JLabel();
        providerComboBox = new javax.swing.JComboBox<>();
        providerLocationPane = new javax.swing.JLayeredPane();
        providerLocationLabel = new javax.swing.JLabel();
        providerLocationField = new javax.swing.JTextField();
        apiKeyPane = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        apiKeyLabel = new javax.swing.JLabel();
        apiKeyInfo = new javax.swing.JLabel();
        apiKeyField = new javax.swing.JPasswordField();
        modelPane = new javax.swing.JLayeredPane();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        gptModelLabel = new javax.swing.JLabel();
        gptModelHelp = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        modelComboBox = new javax.swing.JComboBox<>();
        modelsInfo = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        aiAssistantActivationCheckBox = new javax.swing.JCheckBox();
        enableHintCheckBox = new javax.swing.JCheckBox();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        enableSmartCodeCheckBox = new javax.swing.JCheckBox();
        showDescriptionCheckBox = new javax.swing.JCheckBox();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        cleanDataButton = new javax.swing.JButton();

        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 1));

        classContextPane.setPreferredSize(new java.awt.Dimension(125, 75));
        classContextPane.setLayout(new java.awt.GridLayout(0, 1));

        jLayeredPane7.setPreferredSize(new java.awt.Dimension(125, 40));
        jLayeredPane7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        org.openide.awt.Mnemonics.setLocalizedText(classContextLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextLabel.text")); // NOI18N
        jLayeredPane7.add(classContextLabel);

        classContextHelp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        classContextHelp.setForeground(new java.awt.Color(100, 100, 100));
        classContextHelp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(classContextHelp, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextHelp.text")); // NOI18N
        jLayeredPane7.add(classContextHelp);

        classContextPane.add(jLayeredPane7);

        classContextComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(AIClassContext.values()));
        classContextComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextComboBox.toolTipText")); // NOI18N
        classContextComboBox.setPreferredSize(new java.awt.Dimension(72, 35));
        classContextComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classContextComboBoxActionPerformed(evt);
            }
        });
        classContextPane.add(classContextComboBox);

        jLayeredPane1.add(classContextPane);

        providerPane.setLayout(new javax.swing.BoxLayout(providerPane, javax.swing.BoxLayout.LINE_AXIS));

        jLayeredPane8.setLayout(new java.awt.GridLayout(0, 1));

        org.openide.awt.Mnemonics.setLocalizedText(providerLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.providerLabel.text")); // NOI18N
        jLayeredPane8.add(providerLabel);

        providerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(GenAIProvider.values()));
        providerComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.providerComboBox.toolTipText")); // NOI18N
        providerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane8.add(providerComboBox);

        providerPane.add(jLayeredPane8);

        providerLocationPane.setLayout(new java.awt.GridLayout(0, 1));

        org.openide.awt.Mnemonics.setLocalizedText(providerLocationLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.providerLocationLabel.text")); // NOI18N
        providerLocationPane.add(providerLocationLabel);

        providerLocationField.setText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.providerLocationField.text")); // NOI18N
        providerLocationPane.add(providerLocationField);

        providerPane.add(providerLocationPane);

        apiKeyPane.setLayout(new java.awt.GridLayout(0, 1));

        jLayeredPane2.setLayout(new java.awt.GridLayout());

        org.openide.awt.Mnemonics.setLocalizedText(apiKeyLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.apiKeyLabel.text")); // NOI18N
        jLayeredPane2.add(apiKeyLabel);

        apiKeyInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(apiKeyInfo, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.apiKeyInfo.text")); // NOI18N
        jLayeredPane2.add(apiKeyInfo);

        apiKeyPane.add(jLayeredPane2);

        apiKeyField.setText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.apiKeyField.text")); // NOI18N
        apiKeyPane.add(apiKeyField);

        providerPane.add(apiKeyPane);

        jLayeredPane1.add(providerPane);

        modelPane.setLayout(new java.awt.GridLayout(2, 1));

        jLayeredPane6.setLayout(new javax.swing.BoxLayout(jLayeredPane6, javax.swing.BoxLayout.LINE_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(gptModelLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.gptModelLabel.text")); // NOI18N
        jLayeredPane6.add(gptModelLabel);

        gptModelHelp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gptModelHelp.setForeground(new java.awt.Color(100, 100, 100));
        gptModelHelp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(gptModelHelp, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.gptModelHelp.text")); // NOI18N
        jLayeredPane6.add(gptModelHelp);

        modelPane.add(jLayeredPane6);

        jLayeredPane5.setLayout(new java.awt.GridLayout(1, 2));

        modelComboBox.setEditable(true);
        modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(getModelList((GenAIProvider)providerComboBox.getSelectedItem()).toArray(new String[0])));
        modelComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.modelComboBox.toolTipText")); // NOI18N
        modelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane5.add(modelComboBox);

        modelsInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(modelsInfo, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.modelsInfo.text")); // NOI18N
        jLayeredPane5.add(modelsInfo);

        modelPane.add(jLayeredPane5);

        jLayeredPane1.add(modelPane);

        jLayeredPane4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(aiAssistantActivationCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.aiAssistantActivationCheckBox.text")); // NOI18N
        aiAssistantActivationCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.aiAssistantActivationCheckBox.toolTipText")); // NOI18N
        aiAssistantActivationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiAssistantActivationCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane4.add(aiAssistantActivationCheckBox);

        org.openide.awt.Mnemonics.setLocalizedText(enableHintCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableHintCheckBox.text")); // NOI18N
        enableHintCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableHintCheckBox.toolTipText")); // NOI18N
        enableHintCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableHintCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane4.add(enableHintCheckBox);

        jLayeredPane1.add(jLayeredPane4);

        jLayeredPane9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(enableSmartCodeCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableSmartCodeCheckBox.text")); // NOI18N
        enableSmartCodeCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableSmartCodeCheckBox.toolTipText")); // NOI18N
        jLayeredPane9.add(enableSmartCodeCheckBox);

        org.openide.awt.Mnemonics.setLocalizedText(showDescriptionCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.showDescriptionCheckBox.text")); // NOI18N
        showDescriptionCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.showDescriptionCheckBox.toolTipText")); // NOI18N
        showDescriptionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDescriptionCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane9.add(showDescriptionCheckBox);

        jLayeredPane1.add(jLayeredPane9);

        jLayeredPane3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        org.openide.awt.Mnemonics.setLocalizedText(cleanDataButton, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.cleanDataButton.text")); // NOI18N
        cleanDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanDataButtonActionPerformed(evt);
            }
        });
        jLayeredPane3.add(cleanDataButton);

        jLayeredPane1.add(jLayeredPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classContextComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classContextComboBoxActionPerformed
        AIClassContext selectedContext = (AIClassContext) classContextComboBox.getSelectedItem();
        if (selectedContext != null) {
            classContextHelp.setText(selectedContext.getDescription());
        }
    }//GEN-LAST:event_classContextComboBoxActionPerformed

    private void aiAssistantActivationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiAssistantActivationCheckBoxActionPerformed
        // if unchecked then disable the hint and smart checkbox
        if (!aiAssistantActivationCheckBox.isSelected()) {
            enableHintCheckBox.setEnabled(false);
            enableSmartCodeCheckBox.setEnabled(false);
        } else {
            enableHintCheckBox.setEnabled(true);
            enableSmartCodeCheckBox.setEnabled(true);
        }
    }//GEN-LAST:event_aiAssistantActivationCheckBoxActionPerformed

    private void enableHintCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableHintCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableHintCheckBoxActionPerformed

    private void modelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComboBoxActionPerformed
        String selectedContext = (String) modelComboBox.getSelectedItem();
        if (selectedContext != null && getModel(selectedContext) != null) {
            gptModelHelp.setText(getModel(selectedContext).getDescription());
        } else {
            gptModelHelp.setText("");
        }
    }//GEN-LAST:event_modelComboBoxActionPerformed

    private void cleanDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanDataButtonActionPerformed
        ProjectClassScanner.clear();
        JOptionPane.showMessageDialog(this, "Cache has been cleared successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cleanDataButtonActionPerformed

    private void showDescriptionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDescriptionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showDescriptionCheckBoxActionPerformed

    private void providerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerComboBoxActionPerformed
        GenAIProvider selectedProvider = (GenAIProvider) providerComboBox.getSelectedItem();
        if (selectedProvider == GenAIProvider.DEEPINFRA
                || selectedProvider == GenAIProvider.CUSTOM_OPEN_AI) {
            apiKeyLabel.setVisible(true);
            apiKeyField.setVisible(true);
            apiKeyPane.setVisible(true);
            providerLocationLabel.setVisible(true);
            if (selectedProvider == GenAIProvider.DEEPINFRA) {
                providerLocationField.setText(DEEPINFRA_URL);
            } else {
                providerLocationField.setText("");
            }
            providerLocationField.setVisible(true);
            providerLocationPane.setVisible(true);
        } else if (selectedProvider == GenAIProvider.GOOGLE
                || selectedProvider == GenAIProvider.OPEN_AI
                || selectedProvider == GenAIProvider.MISTRAL
                || selectedProvider == GenAIProvider.ANTHROPIC) {
            apiKeyLabel.setVisible(true);
            apiKeyField.setVisible(true);
            apiKeyPane.setVisible(true);
            providerLocationLabel.setVisible(false);
            providerLocationField.setText("");
            providerLocationField.setVisible(false);
            providerLocationPane.setVisible(false);
        } else {
            apiKeyLabel.setVisible(false);
            apiKeyField.setVisible(false);
            apiKeyPane.setVisible(false);
            providerLocationLabel.setVisible(true);
            providerLocationField.setVisible(true);
            providerLocationPane.setVisible(true);

            if (null != selectedProvider) {
                switch (selectedProvider) {
                    case OLLAMA ->
                        providerLocationField.setText(new OllamaModelFetcher().getAPIUrl());
                    case LM_STUDIO ->
                        providerLocationField.setText(new LMStudioModelFetcher().getAPIUrl());
                    case GPT4ALL ->
                        providerLocationField.setText(new GPT4AllModelFetcher().getAPIUrl());
                }
            }
        }
        if (apiKeyLabel.isVisible()
                && selectedProvider != null
                && !selectedProvider.getApiKeyUrl().isEmpty()) {
            String apiKeyUrl = selectedProvider.getApiKeyUrl();
            apiKeyInfo.setText("<html><a href=''>" + apiKeyUrl + "</a></html>");
            apiKeyInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
            apiKeyInfo.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(apiKeyUrl));
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    apiKeyInfo.setText("<html><a href=''><span style='color:blue;'>" + apiKeyUrl + "</span></a></html>");
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    apiKeyInfo.setText("<html><a href=''>" + apiKeyUrl + "</a></html>");
                }
            });
        }
        if (selectedProvider != null
                && !selectedProvider.getModelInfoUrl().isEmpty()) {
            String modelInfoUrl = selectedProvider.getModelInfoUrl();
            modelsInfo.setText("<html><a href=''>" + modelInfoUrl + "</a></html>");
            modelsInfo.setCursor(new Cursor(Cursor.HAND_CURSOR));
            modelsInfo.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    try {
                        Desktop.getDesktop().browse(new URI(modelInfoUrl));
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    modelsInfo.setText("<html><a href=''><span style='color:blue;'>" + modelInfoUrl + "</span></a></html>");
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    modelsInfo.setText("<html><a href=''>" + modelInfoUrl + "</a></html>");
                }
            });
        }
        if (selectedProvider != null) {
            updateModelComboBox(selectedProvider);
        }
    }//GEN-LAST:event_providerComboBoxActionPerformed

    private void updateModelComboBox(GenAIProvider selectedProvider) {
        modelComboBox.removeAllItems();
        for (String model : getModelList(selectedProvider)) {
            modelComboBox.addItem(model);
        }
        if (modelComboBox.getItemCount() > 0) {
            modelComboBox.setSelectedIndex(0);
        }
    }

    private List<String> getModelList(GenAIProvider selectedProvider) {
        if (selectedProvider == GenAIProvider.OLLAMA
                && !providerLocationField.getText().isEmpty()) {
            OllamaModelFetcher fetcher = new OllamaModelFetcher();
            return fetcher.fetchModelNames(providerLocationField.getText());
        } else if (selectedProvider == GenAIProvider.LM_STUDIO
                && !providerLocationField.getText().isEmpty()) {
            LMStudioModelFetcher fetcher = new LMStudioModelFetcher();
            return fetcher.fetchModelNames(providerLocationField.getText());
        } else if (selectedProvider == GenAIProvider.GPT4ALL
                && !providerLocationField.getText().isEmpty()) {
            GPT4AllModelFetcher fetcher = new GPT4AllModelFetcher();
            return fetcher.fetchModelNames(providerLocationField.getText());
        }
        return MODELS.values().stream()
                .filter(model -> model.getProvider().equals(selectedProvider))
                .map(GenAIModel::getName)
                .collect(Collectors.toList());
    }

    private GenAIModel getModel(String modelName) {
        return MODELS.get(modelName);
    }

    private final PreferencesManager preferencesManager = PreferencesManager.getInstance();

    void load() {
        aiAssistantActivationCheckBox.setSelected(preferencesManager.isAiAssistantActivated());
        classContextComboBox.setSelectedItem(preferencesManager.getClassContext());
        enableHintCheckBox.setSelected(preferencesManager.isHintsEnabled());
        enableSmartCodeCheckBox.setSelected(preferencesManager.isSmartCodeEnabled());

        if (!aiAssistantActivationCheckBox.isSelected()) {
            enableHintCheckBox.setEnabled(false);
            enableSmartCodeCheckBox.setEnabled(false);
        } else {
            enableHintCheckBox.setEnabled(true);
            enableSmartCodeCheckBox.setEnabled(true);
        }

        providerComboBox.setSelectedItem(preferencesManager.getProvider());
        modelComboBox.setSelectedItem(preferencesManager.getModel());
        showDescriptionCheckBox.setSelected(preferencesManager.isDescriptionEnabled());
        GenAIProvider selectedProvider = (GenAIProvider) providerComboBox.getSelectedItem();
        if (selectedProvider == GenAIProvider.CUSTOM_OPEN_AI
                || selectedProvider == GenAIProvider.DEEPINFRA) {
            apiKeyField.setText(preferencesManager.getApiKey(true));
            providerLocationField.setText(preferencesManager.getProviderLocation());
        } else if (selectedProvider == GenAIProvider.GOOGLE
                || selectedProvider == GenAIProvider.OPEN_AI
                || selectedProvider == GenAIProvider.MISTRAL
                || selectedProvider == GenAIProvider.ANTHROPIC) {
            apiKeyField.setText(preferencesManager.getApiKey(true));
        } else if (selectedProvider == GenAIProvider.OLLAMA
                || selectedProvider == GenAIProvider.LM_STUDIO
                || selectedProvider == GenAIProvider.GPT4ALL) {
            providerLocationField.setText(preferencesManager.getProviderLocation());
        }
    }

    void store() {
        preferencesManager.setAiAssistantActivated(aiAssistantActivationCheckBox.isSelected());
        preferencesManager.setClassContext((AIClassContext) classContextComboBox.getSelectedItem());
        preferencesManager.setProvider((GenAIProvider) providerComboBox.getSelectedItem());
        preferencesManager.setModel((String) modelComboBox.getSelectedItem());
        preferencesManager.setHintsEnabled(enableHintCheckBox.isSelected());
        preferencesManager.setSmartCodeEnabled(enableSmartCodeCheckBox.isSelected());
        preferencesManager.setDescriptionEnabled(showDescriptionCheckBox.isSelected());

        GenAIProvider selectedProvider = (GenAIProvider) providerComboBox.getSelectedItem();
        if (selectedProvider == GenAIProvider.CUSTOM_OPEN_AI
                || selectedProvider == GenAIProvider.DEEPINFRA) {
            preferencesManager.setApiKey(new String(apiKeyField.getPassword()));
            preferencesManager.setProviderLocation(providerLocationField.getText());
        } else if (selectedProvider == GenAIProvider.GOOGLE
                || selectedProvider == GenAIProvider.OPEN_AI
                || selectedProvider == GenAIProvider.MISTRAL
                || selectedProvider == GenAIProvider.ANTHROPIC) {
            preferencesManager.setApiKey(new String(apiKeyField.getPassword()));
        } else if (selectedProvider == GenAIProvider.OLLAMA
                || selectedProvider == GenAIProvider.LM_STUDIO
                || selectedProvider == GenAIProvider.GPT4ALL) {
            preferencesManager.setProviderLocation(providerLocationField.getText());
        }
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aiAssistantActivationCheckBox;
    private javax.swing.JPasswordField apiKeyField;
    private javax.swing.JLabel apiKeyInfo;
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JLayeredPane apiKeyPane;
    private javax.swing.JComboBox<AIClassContext> classContextComboBox;
    private javax.swing.JLabel classContextHelp;
    private javax.swing.JLabel classContextLabel;
    private javax.swing.JLayeredPane classContextPane;
    private javax.swing.JButton cleanDataButton;
    private javax.swing.JCheckBox enableHintCheckBox;
    private javax.swing.JCheckBox enableSmartCodeCheckBox;
    private javax.swing.JLabel gptModelHelp;
    private javax.swing.JLabel gptModelLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JComboBox<String> modelComboBox;
    private javax.swing.JLayeredPane modelPane;
    private javax.swing.JLabel modelsInfo;
    private javax.swing.JComboBox<io.github.jeddict.ai.settings.GenAIProvider> providerComboBox;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JTextField providerLocationField;
    private javax.swing.JLabel providerLocationLabel;
    private javax.swing.JLayeredPane providerLocationPane;
    private javax.swing.JLayeredPane providerPane;
    private javax.swing.JCheckBox showDescriptionCheckBox;
    // End of variables declaration//GEN-END:variables
}
