/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.github.jeddict.ai.settings;

import io.github.jeddict.ai.scanner.ProjectClassScanner;
import javax.swing.JOptionPane;

final class AIAssistancePanel extends javax.swing.JPanel {

    private final AIAssistanceOptionsPanelController controller;

    AIAssistancePanel(AIAssistanceOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        classContextLabel = new javax.swing.JLabel();
        classContextHelp = new javax.swing.JLabel();
        classContextComboBox = new javax.swing.JComboBox<>();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        gptModelLabel = new javax.swing.JLabel();
        gptModelHelp = new javax.swing.JLabel();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        providerComboBox = new javax.swing.JComboBox<>();
        modelComboBox = new javax.swing.JComboBox<>();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        aiAssistantActivationCheckBox = new javax.swing.JCheckBox();
        enableHintCheckBox = new javax.swing.JCheckBox();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        enableSmartCodeCheckBox = new javax.swing.JCheckBox();
        showDescriptionCheckBox = new javax.swing.JCheckBox();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        resetKeyButton = new javax.swing.JButton();
        cleanDataButton = new javax.swing.JButton();

        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(125, 75));
        jLayeredPane2.setLayout(new java.awt.GridLayout(0, 1));

        jLayeredPane7.setPreferredSize(new java.awt.Dimension(125, 40));
        jLayeredPane7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        org.openide.awt.Mnemonics.setLocalizedText(classContextLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextLabel.text")); // NOI18N
        jLayeredPane7.add(classContextLabel);

        classContextHelp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        classContextHelp.setForeground(new java.awt.Color(100, 100, 100));
        org.openide.awt.Mnemonics.setLocalizedText(classContextHelp, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextHelp.text")); // NOI18N
        jLayeredPane7.add(classContextHelp);

        jLayeredPane2.add(jLayeredPane7);

        classContextComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(AIClassContext.values()));
        classContextComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.classContextComboBox.toolTipText")); // NOI18N
        classContextComboBox.setPreferredSize(new java.awt.Dimension(72, 35));
        classContextComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classContextComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane2.add(classContextComboBox);

        jLayeredPane1.add(jLayeredPane2);

        jLayeredPane5.setLayout(new java.awt.GridLayout(0, 1));

        jLayeredPane6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(gptModelLabel, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.gptModelLabel.text")); // NOI18N
        jLayeredPane6.add(gptModelLabel);

        gptModelHelp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        gptModelHelp.setForeground(new java.awt.Color(100, 100, 100));
        org.openide.awt.Mnemonics.setLocalizedText(gptModelHelp, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.gptModelHelp.text")); // NOI18N
        jLayeredPane6.add(gptModelHelp);

        jLayeredPane5.add(jLayeredPane6);

        jLayeredPane10.setLayout(new java.awt.GridLayout(1, 0));

        providerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(GenAIProvider.values()));
        providerComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.providerComboBox.toolTipText")); // NOI18N
        providerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                providerComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane10.add(providerComboBox);

        modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(GenAIModel.values()));
        modelComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.modelComboBox.toolTipText")); // NOI18N
        modelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComboBoxActionPerformed(evt);
            }
        });
        jLayeredPane10.add(modelComboBox);

        jLayeredPane5.add(jLayeredPane10);

        jLayeredPane1.add(jLayeredPane5);

        jLayeredPane4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(aiAssistantActivationCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.aiAssistantActivationCheckBox.text")); // NOI18N
        aiAssistantActivationCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.aiAssistantActivationCheckBox.toolTipText")); // NOI18N
        aiAssistantActivationCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiAssistantActivationCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane4.add(aiAssistantActivationCheckBox);

        org.openide.awt.Mnemonics.setLocalizedText(enableHintCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableHintCheckBox.text")); // NOI18N
        enableHintCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableHintCheckBox.toolTipText")); // NOI18N
        enableHintCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableHintCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane4.add(enableHintCheckBox);

        jLayeredPane1.add(jLayeredPane4);

        jLayeredPane9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(enableSmartCodeCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableSmartCodeCheckBox.text")); // NOI18N
        enableSmartCodeCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.enableSmartCodeCheckBox.toolTipText")); // NOI18N
        jLayeredPane9.add(enableSmartCodeCheckBox);

        org.openide.awt.Mnemonics.setLocalizedText(showDescriptionCheckBox, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.showDescriptionCheckBox.text")); // NOI18N
        showDescriptionCheckBox.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.showDescriptionCheckBox.toolTipText")); // NOI18N
        showDescriptionCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDescriptionCheckBoxActionPerformed(evt);
            }
        });
        jLayeredPane9.add(showDescriptionCheckBox);

        jLayeredPane1.add(jLayeredPane9);

        jLayeredPane3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        org.openide.awt.Mnemonics.setLocalizedText(resetKeyButton, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.resetKeyButton.text")); // NOI18N
        resetKeyButton.setToolTipText(org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.resetKeyButton.toolTipText")); // NOI18N
        resetKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetKeyButtonActionPerformed(evt);
            }
        });
        jLayeredPane3.add(resetKeyButton);

        org.openide.awt.Mnemonics.setLocalizedText(cleanDataButton, org.openide.util.NbBundle.getMessage(AIAssistancePanel.class, "AIAssistancePanel.cleanDataButton.text")); // NOI18N
        cleanDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanDataButtonActionPerformed(evt);
            }
        });
        jLayeredPane3.add(cleanDataButton);

        jLayeredPane1.add(jLayeredPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void classContextComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classContextComboBoxActionPerformed
        AIClassContext selectedContext = (AIClassContext) classContextComboBox.getSelectedItem();
        if (selectedContext != null) {
            classContextHelp.setText(selectedContext.getDescription());
        }
    }//GEN-LAST:event_classContextComboBoxActionPerformed

    private void aiAssistantActivationCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiAssistantActivationCheckBoxActionPerformed
        // if unchecked then disable the hint and smart checkbox
        if (!aiAssistantActivationCheckBox.isSelected()) {
            enableHintCheckBox.setEnabled(false);
            enableSmartCodeCheckBox.setEnabled(false);
        } else {
            enableHintCheckBox.setEnabled(true);
            enableSmartCodeCheckBox.setEnabled(true);
        }
    }//GEN-LAST:event_aiAssistantActivationCheckBoxActionPerformed

    private void enableHintCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableHintCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enableHintCheckBoxActionPerformed

    private void modelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComboBoxActionPerformed
        GenAIModel selectedContext = (GenAIModel) modelComboBox.getSelectedItem();
        if (selectedContext != null) {
            gptModelHelp.setText(selectedContext.getDescription());
        }
    }//GEN-LAST:event_modelComboBoxActionPerformed

    private void resetKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetKeyButtonActionPerformed
        preferencesManager.clearApiKey();
        JOptionPane.showMessageDialog(this, "Your API key has been reset successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_resetKeyButtonActionPerformed

    private void cleanDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanDataButtonActionPerformed
        ProjectClassScanner.clear();
        JOptionPane.showMessageDialog(this, "Cache has been cleared successfully!", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cleanDataButtonActionPerformed

    private void showDescriptionCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDescriptionCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showDescriptionCheckBoxActionPerformed

    private void providerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_providerComboBoxActionPerformed
        GenAIProvider selectedProvider = (GenAIProvider) providerComboBox.getSelectedItem();
        if (selectedProvider != null) {
            updateModelComboBox(selectedProvider);
        }
    }//GEN-LAST:event_providerComboBoxActionPerformed

    private void updateModelComboBox(GenAIProvider selectedProvider) {
        modelComboBox.removeAllItems();
        for (GenAIModel model : GenAIModel.values()) {
            if (model.getProvider() == selectedProvider) {
                modelComboBox.addItem(model);
            }
        }
        // Optionally, you can select the first model after filtering
        if (modelComboBox.getItemCount() > 0) {
            modelComboBox.setSelectedIndex(0);
        }
    }
    
    private final PreferencesManager preferencesManager = PreferencesManager.getInstance();

    void load() {
        aiAssistantActivationCheckBox.setSelected(preferencesManager.isAiAssistantActivated());
        classContextComboBox.setSelectedItem(preferencesManager.getClassContext());
        modelComboBox.setSelectedItem(preferencesManager.getModel());
        enableHintCheckBox.setSelected(preferencesManager.isHintsEnabled());
        enableSmartCodeCheckBox.setSelected(preferencesManager.isSmartCodeEnabled());

        if (!aiAssistantActivationCheckBox.isSelected()) {
            enableHintCheckBox.setEnabled(false);
            enableSmartCodeCheckBox.setEnabled(false);
        } else {
            enableHintCheckBox.setEnabled(true);
            enableSmartCodeCheckBox.setEnabled(true);
        }
        
        showDescriptionCheckBox.setSelected(preferencesManager.isDescriptionEnabled());
    }

    void store() {
        preferencesManager.setAiAssistantActivated(aiAssistantActivationCheckBox.isSelected());
        preferencesManager.setClassContext((AIClassContext) classContextComboBox.getSelectedItem());
        preferencesManager.setGptModel((GenAIModel) modelComboBox.getSelectedItem());
        preferencesManager.setHintsEnabled(enableHintCheckBox.isSelected());
        preferencesManager.setSmartCodeEnabled(enableSmartCodeCheckBox.isSelected());
        preferencesManager.setDescriptionEnabled(showDescriptionCheckBox.isSelected());
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aiAssistantActivationCheckBox;
    private javax.swing.JComboBox<AIClassContext> classContextComboBox;
    private javax.swing.JLabel classContextHelp;
    private javax.swing.JLabel classContextLabel;
    private javax.swing.JButton cleanDataButton;
    private javax.swing.JCheckBox enableHintCheckBox;
    private javax.swing.JCheckBox enableSmartCodeCheckBox;
    private javax.swing.JLabel gptModelHelp;
    private javax.swing.JLabel gptModelLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JComboBox<io.github.jeddict.ai.settings.GenAIModel> modelComboBox;
    private javax.swing.JComboBox<io.github.jeddict.ai.settings.GenAIProvider> providerComboBox;
    private javax.swing.JButton resetKeyButton;
    private javax.swing.JCheckBox showDescriptionCheckBox;
    // End of variables declaration//GEN-END:variables
}
